project_name: tgm

env:
  - GO111MODULE=on

build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X tgm/version.Version={{ .Version }} -X tgm/version.CommitSHA={{ .ShortCommit }}
  main: main.go
  binary: tgm
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
    - goos: freebsd
      goarch: arm

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  -
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "tgm/tgm:{{ .Tag }}-amd64"
      - "tgm/tgm:v{{ .Major }}-amd64"
    extra_files:
      - .docker.json
  -
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "tgm/tgm:{{ .Tag }}-arm64"
      - "tgm/tgm:v{{ .Major }}-arm64"
    extra_files:
      - .docker.json
  -
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v6"
    goos: linux
    goarch: arm
    goarm: '6'
    image_templates:
      - "tgm/tgm:{{ .Tag }}-armv6"
      - "tgm/tgm:v{{ .Major }}-armv6"
    extra_files:
      - .docker.json
  -
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v7"
    goos: linux
    goarch: arm
    goarm: '7'
    image_templates:
      - "tgm/tgm:{{ .Tag }}-armv7"
      - "tgm/tgm:v{{ .Major }}-armv7"
    extra_files:
      - .docker.json
docker_manifests:
  - name_template: "tgm/tgm:latest"
    image_templates:
      - "tgm/tgm:{{ .Tag }}-amd64"
      - "tgm/tgm:{{ .Tag }}-arm64"
      - "tgm/tgm:{{ .Tag }}-armv6"
      - "tgm/tgm:{{ .Tag }}-armv7"
  - name_template: "tgm/tgm:{{ .Tag }}"
    image_templates:
      - "tgm/tgm:{{ .Tag }}-amd64"
      - "tgm/tgm:{{ .Tag }}-arm64"
      - "tgm/tgm:{{ .Tag }}-armv6"
      - "tgm/tgm:{{ .Tag }}-armv7"
  - name_template: "tgm/tgm:v{{ .Major }}"
    image_templates:
      - "tgm/tgm:v{{ .Major }}-amd64"
      - "tgm/tgm:v{{ .Major }}-arm64"
      - "tgm/tgm:v{{ .Major }}-armv6"
      - "tgm/tgm:v{{ .Major }}-armv7"
brews:
  - name: tgm
    tap:
      owner: tgm
      name: homebrew-tap
    folder: Formula
    homepage: https://www.teratec.co.kr/html/main.php
    commit_author:
      name: tgm Robot
      email: robot@tgm.org
    description: tgm is a create-your-own-cloud-kind of software where you can install it on a server, direct it to a path and then access your files through a nice web interface
    license: "MIT"